"""add campo telefone ao funcionario

Revision ID: 511d7f1f535b
Revises: bb93e90fa413
Create Date: 2025-06-11 11:42:29.108892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511d7f1f535b'
down_revision: Union[str, None] = 'bb93e90fa413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('telefone', sa.String(), nullable=True))
    op.create_index(op.f('ix_funcionarios_telefone'), 'funcionarios', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funcionarios_telefone'), table_name='funcionarios')
    op.drop_column('funcionarios', 'telefone')
    # ### end Alembic commands ###
